### ISSUE TITLE
IRX imports in Makefile

### ISSUE THREAD

**Issue by jpd002** [unknownbrackets/ps2autotests#14]
I was wondering if you had something in the works regarding building import object files (no idea if that's the right nomenclature) needed to import functions into IOP IRX modules.

If not, I've got something working on my side. I can send a PR with my changes so you can have a look at it.

**Comment by unknownbrackets** [comment]
I haven't gotten there, would definitely appreciate a PR.

-[Unknown]

**Comment by jpd002** [comment]
Alright, I'll build a clean test case and submit the PR.

**Comment by jpd002** [comment]
Submitted #15
