### ISSUE TITLE
Testing Individual VIF commands

### ISSUE THREAD

**Issue by jpd002** [unknownbrackets/ps2autotests#18]
I was thinking of adding a simple test for the MSKPATH3 VIF command. At some point, it would also be interesting to test other VIF commands separately. 

Would that kind of test fit in the `dma/vif` category or would those be better placed in another directory?

**Comment by unknownbrackets** [comment]
I think it belongs in dma/vif.  I wouldn't necessarily be opposed to moving it to the root, though.  Not a strong opinion.  I'm less sure about the gif, it might belong in gs/ but it probably makes more sense in dma?  Obviously gs tests will end up using gif in any case.

Yes, I definitely think it will be good to test all the different vif commands.

The current vif/basic test is really just to ensure that the DMA channel works.  There's a bunch of regs and commands and even unpack types that need individual testing imho.

In contrast, I think the ipu probably belongs on the root (tests/ipu.)  I think of VIFcode as a method to the means of DMA, whereas ipu is really a discrete function.  Memory, timers, and interrupt tests probably also belong on the root, and definitely gs.

Harder to decide about disc/pad/memcard/usb/hdd/net.  I think they also belong on the root but maybe it makes sense to group them under kernel/iop....

-[Unknown]

**Comment by jpd002** [comment]
Sounds good to me. I will add my VIFcode tests to `dma/vif`. Thanks!
